services:
  redis:
    image: redis:7-alpine
    container_name: cinephiles-redis
    ports:
      - "6379:6379"
    # Optional: Saves data to disk every 60 seconds if at least 1 key changed
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: cinephiles-redis-insight
    ports:
      - "8001:5540" # Maps port 8001 on your machine to the internal GUI port
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - redis_insight_data:/data

volumes:
  redis_data:
  redis_insight_data: